[station]
name = "ezmd"
finallist = "/home/jak123/work/tarim/check/ezmd/1/SYN.Sfinallist.dat"
rf_dir = "/home/jak123/work/tarim/check/ezmd/1"
rf_pattern = "{rf_dir}/{event_id}_P_R.sac"
out_dir = "./results/ezmd"

[data]
dt = 0.05
time_start = -2.0
time_end = 30.0
preonset_fallback = 10.0
remove_mean = false
remove_trend = false
apply_filter = false
apply_taper = false
freqmin = 0.05
freqmax = 2.00
filter_order = 2
zerophase = false
time_reference = "b"
baseline_correct = false
baseline_tmin = -2.0
baseline_tmax = -0.2
normalize = "none"
norm_tmin = -1.0
norm_tmax = 8.0
gaussian = 1.0

[pbin]
width = 0.008
step = 0.005
min_events = 10
stack_method = "mean"

[model]
mantle_extra_depth = 80.0
min_lower_crust_thickness = 5.0
plot_depth_max = 70.0
plot_depth_dz = 0.25
plot_vs_bins = 140

[priors]
H_sed_center = 8.0
H_sed_sigma = 2.0
Vs_mantle_center = 4.60
Vs_mantle_sigma = 0.15
VpVs_mantle_center = 1.78
VpVs_mantle_sigma = 0.05

[weights]
cc = 0.2
nrmse = 0.8
prior = 1.0

[na]
n_initial = 5000
n_samples = 200
n_resample = 50
n_iterations = 100
top_fraction = 0.25
seed = 20260422

[appraisal]
enabled = true
n_resample = 75000
n_walkers = 15
start_fraction = 0.25
verbose = false
seed = 20260422
temperature_mode = "best_iqr"
temperature = 0.01
temperature_top_fraction = 0.10
temperature_min = 0.001

[parallel]
enabled = true
n_workers = 0
chunksize = 3
start_method = "spawn"
maxtasksperchild = 0

[bounds]
H_sed = [6, 10]
sed_ratio1 = [0.10, 0.80]
Vs_sed1 = [0.5, 3.00]
Vs_sed2 = [1.50, 3.50]
VpVs_sed = [1.80, 2.8]
H_uc = [15.0, 30.0]
Vs_uc = [3.20, 3.90]
VpVs_uc = [1.55, 1.85]
H_moho = [35.0, 55.0]
Vs_lc = [3.60, 4.50]
VpVs_lc = [1.65, 1.90]
Vs_mantle = [4.40, 4.90]
VpVs_mantle = [1.75, 1.90]
